In [2]:
# importing the numpy library
import numpy as np

**Question 01:Write a NumPy program to create an array of all even integers from 30 to 70.**

In [3]:
# This solution includes the end poinst as well
array_30_to_70 = np.arange(start=30, stop=70, step=2)
array_30_to_70

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68])

**Question 02:Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.**

In [4]:
std_normal = np.random.normal(size=15)
std_normal

array([-1.37730096, -1.97087032, -0.1521938 , -0.22983463,  0.13225274,
       -0.63916108, -0.99130898, -0.82043482, -0.17666592,  0.13499865,
       -0.09187352, -0.31416359, -1.47188281, -0.54822144, -1.85673018])

**Question 03: How to compute the cross-product of two matrices in NumPy?**

In [5]:
# Since the vector/cross product is reserved only for vectors
# The vector product of matrices isn't possible through conventional methods
# however numpy has a different take on this
# it calculate the cross-product of the corresponding row vectors in both the matrices

matrix_A = np.array([
    [1, 2, 3],
    [1, 2, 3]
])
matrix_B = np.array([
    [4, 5, 6],
    [4, 5, 6]
])

cross_product = np.cross(matrix_A, matrix_B)
cross_product

array([[-3,  6, -3],
       [-3,  6, -3]])

**Question 04: How to compute the determinant of an array using NumPy?**

In [6]:
# the expected answer is 63
A = np.array([
    [1, 3, -2],
    [0, 5, 1],
    [4, -1, 2]
])
det_A = np.linalg.det(A)
det_A

62.99999999999999

**Question 05: How to create a 3x3x3 array with random values using NumPy?**

In [7]:
# 3x3x3 means making 3 2d matrix of size 3x3
arr_3x3x3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ],
    [
        [11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
    ],
    [
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
    ]
])

arr_3x3x3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

**Question 05: How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?**


In [8]:
random_array = np.random.random(size=(5,5))
print(random_array)

print("Max:", random_array.max())
print("Min:", random_array.min())

[[0.14568003 0.90223208 0.39109269 0.59278166 0.3452079 ]
 [0.13816906 0.25421257 0.40406287 0.93074696 0.27974947]
 [0.96054601 0.75107363 0.13297319 0.07010616 0.60508667]
 [0.77862126 0.8020163  0.08983615 0.57787073 0.95955367]
 [0.79006228 0.79029876 0.8418992  0.32521724 0.66858192]]
Max: 0.9605460120981514
Min: 0.07010615796936703


**Question 06: How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?**

In [10]:
np.random.seed(10) # the seed is for generating the same random array every time
random_array = np.random.randint(1, 10, size=(5,5))
print(random_array)

print("Mean: ", random_array.mean(axis=1)) # here (axis=1) means 2nd axis
print("Standard Deviation: ", random_array.std(axis=1))
print("Variance:", random_array.var(axis=1))

[[5 1 2 1 2]
 [9 1 9 7 5]
 [4 1 5 7 9]
 [2 9 5 2 4]
 [7 6 4 7 2]]
Mean:  [2.2 6.2 5.2 4.4 5.2]
Standard Deviation:  [1.46969385 2.99332591 2.71293199 2.57681975 1.93907194]
Variance: [2.16 8.96 7.36 6.64 3.76]
